FROM ubuntu

RUN mkdir /opt/yara_service

COPY . /opt/yara_service

COPY config/aws /root/.aws

WORKDIR /opt/yara_service

RUN apt-get update  -y \
    && apt-get install git -y \
    && apt-get install pip -y \
    && pip install -r yara_integration/requirements.txt

RUN python3 yara_integration/yara_rules_download.py

#TODO: need to create cronjob that updates the rules every 2 hours

CMD ["python3", "yara_integration/yara_python_script.py"]