FROM ubuntu:latest

LABEL maintainer="Abhiram Sarja <sarja.a@northeastern.edu>"
WORKDIR /revisor-clamav

# Copy Revisor backend code and related utility files into the image/container
COPY backend/ ./backend/
COPY clamav_engine/ ./clamav_engine/

# Copy the AWS credential files into the image/container
COPY config/aws /root/.aws

USER root

RUN apt-get update  -y \
    && apt-get install pip -y \
    && pip install -r backend/requirements.txt

CMD ["python3", "clamav_engine/clamav.py"]
