FROM ubuntu:latest

LABEL maintainer="Abhiram Sarja <sarja.a@northeastern.edu>"
WORKDIR /revisor-backend

# Copy Revisor backend code and related utility files into the image/container
COPY backend/ ./backend/

# Copy the AWS credential files into the image/container
COPY config/aws /root/.aws

USER root

ENV REVISOR_SERVER_PORT=5000

RUN apt-get update  -y \
    && apt-get install pip -y \
    && pip install -r backend/requirements.txt

CMD ["python3", "backend/revisor.py"]

CMD ["python3", "backend/scan_status_monitor.py"]
