version: '3.8'
services:
  backend:
    container_name: rev_backend
    hostname: backend.revisor.project.com
    build:
      context: ../
      dockerfile: ./docker_files/Dockerfile_backend
    ports:
      - "5000:5000"
    environment:
      CERT_PEM: "../config/certs/backend/cert.pem"
      SERVER_PEM: "../config/certs/backend/server.pem"   # Keep the certificates (.PEM) inside <config/certs/backend/> folder
      REVISOR_EMAIL: "<EMAIL>"
      REVISOR_EMAIL_PASSWORD: "<APP_PASSWORD>"  # Please enter the APP Password of the Google account
  frontend:
    container_name: rev_frontend
    hostname: frontend.revisor.project.com
    build:
      context: ../
      dockerfile: ./docker_files/Dockerfile_frontend
    ports:
      - "80:80"
      - "443:443"
  virustotal:
    container_name: rev_virustotal
    hostname: virustotal.revisor.project.com
    build:
      context: ../
      dockerfile: ./docker_files/Dockerfile_vt
    environment:
      VT_API_KEY: "<vt-api-Key>"
  yara:
    container_name: rev_yara
    hostname: yara.revisor.project.com
    build:
      context: ../
      dockerfile: ./docker_files/Dockerfile_yara
  clamavdaemon: # ClamAV official docker image
    image: clamav/clamav:0.105.1-1
    container_name: clamavd
    ports:
      - "3310:3310"
  cra:  # ClamAV Rest API - official image
    image: benzino77/clamav-rest-api
    container_name: cra
    depends_on:
      clamavdaemon:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
      APP_PORT: 8080
      APP_FORM_KEY: FILE
      APP_MORGAN_LOG_FORMAT: combined
      APP_MAX_FILE_SIZE: 200214400  # Max size of ~200 MB
      CLAMD_IP: XXX.XXX.XXX.XXX  # IP Address of the host machine
      CLAMD_PORT: 3310
      CLAMD_TIMEOUT: 30000
  clamav:
    container_name: rev_clamav
    hostname: clamav.revisor.project.com
    build:
      context: ../
      dockerfile: ./docker_files/Dockerfile_clamav
    ports:
      - "8081:8081"
    links:
      - cra
    depends_on:
      cra:
        condition: service_started
