FROM ubuntu

RUN mkdir /opt/vt_service

COPY ../ /opt/vt_service

COPY ../config/aws /root/.aws

WORKDIR /opt/vt_service

RUN apt-get update  -y \
    && apt-get install pip -y \
    && pip install -r virus_total_integration/requirements.txt

CMD ["python3", "virus_total_integration/vt_script.py"]
