FROM ubuntu:latest

LABEL maintainer="Abhiram Sarja <sarja.a@northeastern.edu>"
WORKDIR /revisor-backend

# Copy Revisor backend code and related utility files into the image/container
COPY ../backend/ ./backend/
# Copy the AWS credential files into the image/container
COPY ../config/aws /root/.aws

# Copy the certificates into the image/container
COPY ../config/certs config/certs

ENV REVISOR_SERVER_PORT=5000

USER root

RUN apt-get update  -y \
    && apt-get install pip -y \
    && pip install -r backend/requirements.txt

CMD ["python3", "backend/revisor.py"]
